apiVersion: v1
kind: Service
metadata:
  name: misskey
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
  selector:
    app: misskey
